### ISSUE TITLE
Falsche Adresse im Mitgliedsbeitrag

### ISSUE THREAD

**Issue by lukasbisdorf** [Freifunk-Rhein-Neckar/propaganda#3]
Im Mitgliedsbeitrag stimmt die Adresse für den Zahlungsempfänger der Lastschrift nicht.
Hier müsste es Fichtelstr. anstelle von Fichtestr. heißen.

@silsha Könntest du evtl. noch die Source hochladen?

**Comment by silsha** [comment]
@lukasbisdorf Die PDF kannst du einfach im Illustrator öffnen. Ich ändere es gleich.

**Comment by nazco** [comment]
Ähm nein Fichtesstr. ist schon richtig gewesen.

**Comment by lukasbisdorf** [comment]
Wut. Sorry dachte es währe die fichtelstraße.
